"""
Django settings for my_project project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import environ



load_dotenv()  # Load environment variables(for secure sendgrid api key)
# Initialize environ and read the .env file
env = environ.Env()
environ.Env.read_env(os.path.join(os.path.dirname(os.path.dirname(__file__)), ".env"))


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-vul4^mldb$*-^d6x*(opg&20b%$m78&)at1flbaj8!39=!5p80"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "accounts.apps.AccountsConfig",    #added manually copy from apps.py file
    "main.apps.MainConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    #for automatic reloading
    "django_browser_reload",  


    # added manually(for tailwind setup)
    "tailwind",
    "theme",

    # Allauth apps
    "django.contrib.sites",   ## Required for social authentication
    'allauth',
    'allauth.account',   # this is not our account app (this is provide by allauth)
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',    # google login provider
    # 'allauth.socialaccount.providers.github',    # github login provider
]

SITE_ID = 1  # Required for django-allauth

# added manually
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default authentication
    'allauth.account.auth_backends.AuthenticationBackend',  # Allauth authentication
]

# added manually (login with google)
ACCOUNT_LOGIN_METHODS = {"username", "email"}  # accepts both 
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]  # Required signup fields(here not mention user_type because that is custom and not provided by allauth)
ACCOUNT_EMAIL_VERIFICATION = "none"  # Change to "mandatory" if you want verification
LOGIN_REDIRECT_URL = "/accounts/social-loader"  # Redirect after login
LOGOUT_REDIRECT_URL = "/accounts/login"  # Redirect after logout
ACCOUNT_SIGNUP_REDIRECT_URL = "/accounts/social-loader"
SOCIALACCOUNT_LOGIN_ON_GET = True  # Bypass intermediate page
ACCOUNT_ADAPTER = "accounts.adapter.MyAccountAdapter"    # here added because we create a adapter file in account folder

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["email", "profile"],
        "AUTH_PARAMS": {"access_type": "online"},
        "APP": {
            "client_id": env("GOOGLE_CLIENT_ID"),
            "secret": env("GOOGLE_CLIENT_SECRET"),
            "key": "",
        }
    }
}








# added manually (for tailwind)
TAILWIND_APP_NAME = "theme"
INTERNAL_IPS = ['127.0.0.1']

#added manually( for account app)
AUTH_USER_MODEL = 'accounts.CustomUser'   # Custom user model # here account is app name and CustomUser is db table name
LOGIN_REDIRECT_URL = 'dashboard'
LOGIN_URL = 'login'



MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
    "allauth.account.middleware.AccountMiddleware",
        
    "django_browser_reload.middleware.BrowserReloadMiddleware",   #add by us for automatic reloading((added manually))

]

ROOT_URLCONF = "my_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],     #added manually
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "my_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

#added seperatly(for choose image from browser)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# added manually
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]   
NPM_BIN_PATH = "C:/Program Files/nodejs/npm.cmd"   # added manually (for tailwind)



