# Generated by Django 5.1.7 on 2025-04-02 06:15

from django.db import migrations
from django.db import models



class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
            migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(max_length=10, choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer'),
        ),

    ]
