# Generated by Django 5.1.7 on 2025-04-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="education",
            field=models.CharField(
                blank=True,
                help_text="Your educational background",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                blank=True,
                help_text="Languages you speak or code in",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="linkedin_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="project_link",
            field=models.URLField(
                blank=True, help_text="Portfolio or live project link", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="video",
            field=models.URLField(
                blank=True,
                help_text="Link to your intro video (YouTube, etc.)",
                null=True,
            ),
        ),
    ]
