# Generated by Django 5.1.7 on 2025-04-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_education_userprofile_github_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="website",
        ),
    ]
