# Generated by Django 5.1.7 on 2025-04-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_userprofile_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="job_title",
            field=models.CharField(default="Python Developer", max_length=255),
        ),
    ]
